Repository Tyranex/Pacific-Sector, pull requests merged in 2025-04, with the labels that each got.

#5 PR to test automated changelogs, please ignore
  Resources/Prototypes/bar_signs.yml
Labels: S: Untriaged, size/XS

#6 Removed dummy update
  Resources/Prototypes/bar_signs.yml
Labels: S: Untriaged

#9 Rules implementation
  Content.Shared/CCVar/CCVars.Server.cs
  Resources/Prototypes/Guidebook/rules.yml
  Resources/ServerInfo/Guidebook/ServerRules/Pacific/CoreRules/RuleSC1Admins.xml
  Resources/ServerInfo/Guidebook/ServerRules/Pacific/CoreRules/RuleSC2Respect.xml
  Resources/ServerInfo/Guidebook/ServerRules/Pacific/CoreRules/RuleSC3NSFW.xml
  Resources/ServerInfo/Guidebook/ServerRules/Pacific/CoreRules/RuleSC4CurrentRound.xml
  Resources/ServerInfo/Guidebook/ServerRules/Pacific/CoreRules/RuleSC5Cheats.xml
  Resources/ServerInfo/Guidebook/ServerRules/Pacific/CoreRules/RuleSC6Minimod.xml
  Resources/ServerInfo/Guidebook/ServerRules/Pacific/CoreRules/RuleSC7Privacy.xml
  Resources/ServerInfo/Guidebook/ServerRules/Pacific/CoreRules/RuleSC8Bigot.xml
  Resources/ServerInfo/Guidebook/ServerRules/Pacific/RPRules/RuleSRP1Universe.xml
  Resources/ServerInfo/Guidebook/ServerRules/Pacific/RPRules/RuleSRP2Character.xml
  Resources/ServerInfo/Guidebook/ServerRules/Pacific/RPRules/RuleSRP3Escalation.xml
  Resources/ServerInfo/Guidebook/ServerRules/Pacific/RPRules/RuleSRP4Alert.xml
  Resources/ServerInfo/Guidebook/ServerRules/Pacific/RPRules/RuleSRP5ValidHunt.xml
  Resources/ServerInfo/Guidebook/ServerRules/Pacific/Rules.xml
Labels: S: Untriaged, size/M

#10 Added missing locale files for Vulp markings
  Resources/Locale/en-US/_DV/markings/vulpkanin.ftl
Labels: S: Untriaged, size/M

#13 Changed the targeted changelog file for discord webhook
  Tools/actions_changelog_rss.py
Labels: S: Untriaged, size/XS

#14 Banana
  Resources/Maps/_Pacific/Shuttles/cargo_banana.yml
  Resources/Maps/_Pacific/banana.yml
  Resources/Prototypes/_Impstation/Entities/Markers/Spawners/mobs.yml
  Resources/Prototypes/_Impstation/Entities/Mobs/NPCs/miscellaneous.yml
  Resources/Prototypes/_pacific/Maps/banana.yml
Labels: S: Untriaged, size/XL

#12 Banana map port
  Resources/Maps/_Pacific/banana.yml
  Resources/Prototypes/_pacific/Maps/banana.yml
Labels: S: Untriaged, size/XL

#15 Added banana to map tests and rotation
  Content.IntegrationTests/Tests/PostMapInitTest.cs
  Resources/Prototypes/Maps/Pools/default.yml
Labels: S: Untriaged, size/XS

#16 Fixed Discord webhook targetting the wrong changelog
  Tools/actions_changelogs_since_last_run.py
Labels: S: Untriaged, size/XS

#20 Unshaded components
  Content.Client/Humanoid/HumanoidAppearanceSystem.cs
  Content.Shared/Humanoid/Markings/MarkingPrototype.cs
  Tools/markings/markings/prototypes.go
Labels: S: Untriaged, size/S

#22 Added two lines to make it look nicer and probably work nicer
  Resources/Prototypes/_Impstation/Entities/Mobs/Customization/Markings/generic.yml
Labels: S: Untriaged, size/XS
